---
- hosts: localhost
  connection: localhost
  remote_user: centos
  tasks:
    - name: Create a java container
      community.docker.docker_container:
        name: java
        image: saidamo/java:apps
        state: started
        restart: yes
        ports:
          - "80:8080"
